CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_ACTIVOS_FIJOS_AREAS_VALORACION" AS
SELECT
COALESCE(T0."Code",'') As ID,
COALESCE(T0."Descr",'') As NOMBRE,
COALESCE(T0."AreaType",'') As TIPO
FROM ODPA T0
WHERE 1=1 


