CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_ACTIVOS_FIJOS_CLASES" AS
SELECT
COALESCE(T0."Code",'') As ID,
COALESCE(T0."Name",'') As NOMBRE,
COALESCE(T0."AssetType",'') As TIPO
FROM OACS T0
WHERE 1=1 


