CREATE VIEW SEI_VIEW_DW_PRECIOS_ENTREGA AS
SELECT 
COALESCE(T0."DocEntry",-1) AS DOCENTRY,
COALESCE(T0."DocNum",-1) AS DOCNUM,
CONVERT(NVARCHAR,COALESCE(T0."DocDate", 0), 112) As DOCDATE, 
CONVERT(NVARCHAR,COALESCE(T0."DocDueDate", 0), 112) As DOCDUEDATE, 
COALESCE(T0."DocStatus",'O') AS DOCSTATUS,
COALESCE(T0."DocCur",'EUR') AS DOCCUR,
COALESCE(T0."Canceled",'N') AS CANCELED,
COALESCE(T1."CardCode",'') AS CARDCODE,
COALESCE(T1."CardName",'') CARDNAME,
COALESCE(T1."LicTradNum",'') LICTRADNUM,
COALESCE(T2."CardCode",'') AGENTCARDCODE,
COALESCE(T2."CardName",'') AGENTCARDNAME,
COALESCE(T2."LicTradNum",'') AS AGENTLICTRADNUM,
COALESCE(T0."Ref1",'') AS REF1,
COALESCE(T0."ExpCustom",0) AS EXPCUSTOM,
COALESCE(T0."ActCustom",0) AS ACTCUSTOM,
CONVERT(NVARCHAR,COALESCE(T0."CustDate", 0), 112) As CUSTDATE, 
COALESCE(T0."CostSum",0) AS COSTSUM,
COALESCE(T0."DocTotal",0) AS DOCTOTAL
FROM OIPF T0 WITH(NOLOCK)
LEFT JOIN OCRD T1 WITH(NOLOCK) ON T1."CardCode"=T0."CardCode"
LEFT JOIN OCRD T2 WITH(NOLOCK) ON T2."CardCode"=T0."AgentCode"
WHERE 1=1 
