CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_LLAMADAS_ESTADO" AS 
SELECT
COALESCE(T0."statusID", -1) As ID,
COALESCE(T0."Name",'') As NOMBRE,
COALESCE(T0."Descriptio",'') As DESCRIPCION
FROM OSCS T0
WHERE 1=1 
And T0."Active"='Y'

