CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_LLAMADAS_SERVICIO" AS 
SELECT 
COALESCE(T0."BPType",'') As "TIPO",
COALESCE(T0."DocNum",-1) As "DOCNUM",
COALESCE(T0."callID",-1) As "IDLLAMADA",
COALESCE(T0."createDate",CURRENT_DATE) As "CREATEDATE",
COALESCE(T0."createTime",0) As "CREATETIME",
COALESCE(T0."customer",'') As "IDINTERLOCUTOR",
COALESCE(T0."custmrName",'') As "RAZONSOCIAL",
COALESCE(T6."Name",'') As "PERSONACONTACTO",
COALESCE(T0."subject",'') As "ASUNTO",
COALESCE(T0."NumAtCard",'') As "NUMATCARD",
COALESCE(T0."manufSN",'') As "NUMEROSERIEFABRICANTE",
COALESCE(T0."internalSN",'') As "NUMEROSERIE",
COALESCE(T0."itemCode",'') As "ARTICULO",
COALESCE(T0."itemName",'') As "DESCRIPCION",
'' As "REFERENCIAEXTERNA",
COALESCE(T8."CardCode",'') As "IDINTERLOCUTORDEFECTO",
COALESCE(T8."CardName",'') As "RAZONSOCIALDEFECTO",
COALESCE(T1."Name",'') As "ESTADO",
COALESCE(T0."priority",'') As "PRIORIDAD",
COALESCE(T2."Name",'') As "ORIGEN",
COALESCE(T3."Name",'') As "TIPOPROBLEMA",
COALESCE(T4."Name",'') As "SUBTIPOPROBLEMA",
COALESCE(T5."Name",'') As "TIPOLLAMADA",
COALESCE(T9."firstName",'') || ' ' || COALESCE(T9."lastName",'') As "TECNICO",
CASE WHEN COALESCE(T0."isQueue",'N')='Y' THEN 'S' ELSE 'N' END As "ESCOLA",
COALESCE(T10."descript",'') As "COLA",
COALESCE(TO_NVARCHAR(T0."descrption"),'') As "COMENTARIOS"
FROM OSCL T0 
LEFT JOIN OSCS T1 ON T1."statusID"=T0."status"
LEFT JOIN OSCO T2 ON T2."originID"=T0."origin"
LEFT JOIN OSCP T3 ON T3."prblmTypID"=T0."problemTyp"
LEFT JOIN OPST T4 ON T4."ProSubTyId"=T0."ProSubType"
LEFT JOIN OSCT T5 ON T5."callTypeID"=T0."callType"
LEFT JOIN OCPR T6 ON T6."CntctCode"=T0."contctCode" And T6."CardCode"=T0."customer"
LEFT JOIN OITM T7 ON T7."ItemCode"=T0."itemCode"
LEFT JOIN OCRD T8 ON T8."CardCode"=T7."CardCode"
LEFT JOIN OHEM T9 ON T9."empID"=T0."technician"
LEFT JOIN OQUE T10 ON T10."queueID"=T0."Queue"


