CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_LLAMADAS_TIPO" AS 
SELECT
COALESCE(T0."callTypeID", -1) As ID,
COALESCE(T0."Name",'') As NOMBRE,
COALESCE(T0."Descriptio",'') As DESCRIPCION
FROM OSCT T0
WHERE 1=1 
And T0."Active"='Y'

