CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_LLAMADAS_COLA" AS 
SELECT
COALESCE(T0."queueID", -1) As ID,
COALESCE(T0."descript",'') As NOMBRE,
COALESCE(T0."manager",-1) As RESPONSABLE,
COALESCE(T0."email",'') As EMAIL
FROM OQUE T0 
WHERE 1=1 
And T0."inactive"='N'


