CREATE VIEW SEI_VIEW_DW_PRECIOS_ENTREGA AS
SELECT 
COALESCE(T0."DocEntry",-1) AS DOCENTRY,
COALESCE(T0."DocNum",-1) AS DOCNUM,
TO_NVARCHAR(T0."DocDate",'YYYYMMDD') As DOCDATE, 
TO_NVARCHAR(T0."DocDueDate",'YYYYMMDD') As DOCDUEDATE, 
COALESCE(T0."DocStatus",'O') AS DOCSTATUS,
COALESCE(T0."DocCur",'EUR') AS DOCCUR,
COALESCE(T0."Canceled",'N') AS CANCELED,
COALESCE(T1."CardCode",'') AS CARDCODE,
COALESCE(T1."CardName",'') CARDNAME,
COALESCE(T1."LicTradNum",'') LICTRADNUM,
COALESCE(T2."CardCode",'') AGENTCARDCODE,
COALESCE(T2."CardName",'') AGENTCARDNAME,
COALESCE(T2."LicTradNum",'') AS AGENTLICTRADNUM,
COALESCE(T0."Ref1",'') AS REF1,
COALESCE(T0."ExpCustom",0) AS EXPCUSTOM,
COALESCE(T0."ActCustom",0) AS ACTCUSTOM,
TO_NVARCHAR(T0."CustDate",'YYYYMMDD') As CUSTDATE, 
COALESCE(T0."CostSum",0) AS COSTSUM,
COALESCE(T0."DocTotal",0) AS DOCTOTAL
FROM OIPF T0 
LEFT JOIN OCRD T1 ON T1."CardCode"=T0."CardCode"
LEFT JOIN OCRD T2 ON T2."CardCode"=T0."AgentCode"
WHERE 1=1 
