CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_FACTURAS_ANTICIPO" AS

--FACTURAS ANTICIPO COMPRA
SELECT 
T0."DocEntry" As DOCENTRY, 
T0."DocNum" As DOCNUM,  
TO_NVARCHAR(T0."DocDate",'YYYYMMDD') As DOCDATE,
T1."CardType" As CARDTYPE, 
T0."CardCode" As CARDCODE, 
T0."CardName" As CARDNAME, 
T0."LicTradNum" AS LICTRADNUM, 
COALESCE(T0."NumAtCard",'') As NUMATCARD,
T0."DocTotal" AS DOCTOTAL, 
T0."DocCur" As DOCCUR, 
T0."PaidToDate" AS PAIDTODATE, 
T0."DpmAppl" AS DPMAPPL
FROM ODPO T0 
JOIN OCRD T1 ON T1."CardCode"=T0."CardCode"
WHERE 1=1
And T0."DpmAppl"=0
And T0."PaidToDate">0
And T1."frozenFor"='N'

UNION ALL

--FACTURAS ANTICIPO VENTA
SELECT 
T0."DocEntry" As DOCENTRY, 
T0."DocNum" As DOCNUM,  
TO_NVARCHAR(T0."DocDate",'YYYYMMDD') As DOCDATE,
T1."CardType" As CARDTYPE, 
T0."CardCode" As CARDCODE, 
T0."CardName" As CARDNAME, 
T0."LicTradNum" AS LICTRADNUM, 
COALESCE(T0."NumAtCard",'') As NUMATCARD,
T0."DocTotal" AS DOCTOTAL, 
T0."DocCur" As DOCCUR, 
T0."PaidToDate" AS PAIDTODATE, 
T0."DpmAppl" AS DPMAPPL
FROM ODPI T0 
JOIN OCRD T1 ON T1."CardCode"=T0."CardCode"
WHERE 1=1
And T0."DpmAppl"=0
And T0."PaidToDate">0
And T1."frozenFor"='N'




