CREATE VIEW SEI_VIEW_DW_ASIENTOS_MODELOS AS 
SELECT
COALESCE(T0."TrtCode", '') As ID,
COALESCE(T0."Dscription",'') As NOMBRE,
CASE WHEN COALESCE(T0."AutoVat",'N')='Y' THEN 'S' ELSE 'N' END As IVAAUTOMATICO,
CASE WHEN COALESCE(T0."DeferedTax",'N')='Y' THEN 'S' ELSE 'N' END As IMPUESTOSDIFERIDOS,
CASE WHEN COALESCE(T0."ManageWTax",'N')='Y' THEN 'S' ELSE 'N' END As GESTIONIMPUESTOS
FROM OTRT T0 WITH(NOLOCK)
WHERE 1=1 


