CREATE VIEW SEI_VIEW_DW_ASIENTOS_OPERACIONES AS 
SELECT
COALESCE(T0."TrnsCode", '') As ID,
COALESCE(T0."TrnsCodDsc",'') As NOMBRE
FROM OTRC T0 WITH(NOLOCK)
WHERE 1=1 
And COALESCE(T0."Locked",'N')='N'
