CREATE VIEW SEI_VIEW_DW_ACTIVIDADES AS 
SELECT 
COALESCE(T0."ClgCode",-1) AS "IDACTIVIDAD",
COALESCE(T0."CardCode",'') AS "IDINTERLOCUTOR",
COALESCE(T4."CardName",'') AS "RAZONSOCIAL",
COALESCE(T5."Name",'') As "PERSONACONTACTO",
COALESCE(T0."Action",'') AS "ACTIVIDAD",
COALESCE(T1."Name",'') AS "TIPO",
COALESCE(T2."Name",'') AS "ASUNTO",
COALESCE(T0."AttendEmpl",0) AS "EMPLEADOASIGNADO",
COALESCE(T0."AttendUser",0) AS "USUARIOASIGNADO",
COALESCE(T0."Details",'') AS "COMENTARIOS",
COALESCE(T0."Recontact",GETDATE()) AS "FECHAINICIO",
COALESCE(T0."BeginTime",0) AS "HORAINICIO",
COALESCE(T0."endDate",GETDATE()) AS "FECHAFIN",
COALESCE(T0."ENDTime",0) AS "HORAFIN",
COALESCE(T0."Priority",'') AS "PRIORIDAD",
COALESCE(T3."Name",'') AS "EMPLAZAMIENTO",
COALESCE(T0."RecurPat",'') AS "REPETICION"
FROM OCLG T0 WITH(NOLOCK)
LEFT JOIN OCLT T1 WITH(NOLOCK) ON T1."Code"=T0."CntctType"
LEFT JOIN OCLS T2 WITH(NOLOCK) ON T2."Code"=T0."CntctSbjct"
LEFT JOIN OCLO T3 WITH(NOLOCK) ON T3."Code"=T0."Location"
LEFT JOIN OCRD T4 WITH(NOLOCK) ON T4."CardCode"=T0."CardCode"
LEFT JOIN OCPR T5 WITH(NOLOCK) ON T5."CntctCode"=T0."CntctCode" And T5."CardCode"=T0."CardCode"
WHERE 1=1
And T0."inactive"='N'



