CREATE VIEW SEI_VIEW_DW_VALORES_VALIDOS AS
SELECT 
COALESCE(T0."TableID",'') As TABLAID,
COALESCE(T0."FieldID",-1) As CAMPOID,
COALESCE(T0."AliasID",'') As ALIASID,
COALESCE(T0."Descr",'') As NOMBRE,
COALESCE(T0."Dflt",'') As VALORVALIDODEFECTO,
(SELECT COALESCE(X0."FldValue",'') + '||' FROM UFD1 X0 WITH(NOLOCK) WHERE X0."TableID"=T0."TableID" And X0."FieldID"=T0."FieldID" ORDER BY X0."IndexID" ASC for xml path(''))  As VALORESVALIDOSID, 
(SELECT COALESCE(X0."Descr",'') + '||' FROM UFD1 X0 WITH(NOLOCK) WHERE X0."TableID"=T0."TableID" And X0."FieldID"=T0."FieldID" ORDER BY X0."IndexID" ASC for xml path(''))  As VALORESVALIDOSNOMBRE
FROM CUFD T0 WITH(NOLOCK)
JOIN UFD1 T1 WITH(NOLOCK) ON T1."TableID"=T0."TableID" And T1."FieldID"=T0."FieldID"
WHERE 1=1
GROUP BY 
T0."TableID",
T0."FieldID",
T0."AliasID",
T0."Descr",
T0."Dflt"

