CREATE VIEW SEI_VIEW_DW_TASAS_CAMBIO AS 
SELECT 
COALESCE(T0."RateDate",GETDATE()) As FECHA,
COALESCE(T0."Currency",'') As MONEDA,
COALESCE(T0."Rate", 0) As TASA
FROM ORTT T0 WITH(NOLOCK)
WHERE 1=1 


