CREATE VIEW SEI_VIEW_DW_SERIES AS 
SELECT
COALESCE(T0."Series",-1) As ID,
COALESCE(T0."SeriesName",'') As NOMBRE,
COALESCE(T0."ObjectCode", '') As OBJTYPE,
CASE WHEN COALESCE(T0."IsManual",'N')='Y' THEN 'S' ELSE 'N' END As MANUAL,
COALESCE(T0."InitialNum",-1) As NUMEROINICIAL,
COALESCE(T0."NextNumber",-1) As SIGUIENTENUMERO,
COALESCE(T0."LastNum",-1) As ULTIMONUMERO,
COALESCE(T0."BeginStr",'') As PREFIJO,
COALESCE(T0."EndStr",'') As SUFIJO,
COALESCE(T0."NumSize",-1) As LONGITUD
FROM NNM1 T0 WITH(NOLOCK)
WHERE 1=1 
And T0."IsForCncl"<>'Y'
And T0."Locked"<>'Y'

