CREATE VIEW SEI_VIEW_DW_CENTROS_COSTE AS 
SELECT
COALESCE(T0."PrcCode",'') As ID,
COALESCE(T0."PrcName", '') As NOMBRE,
COALESCE(T0."DimCode",	-1) As DIMENSION,
COALESCE(T0."CCOwner",	-1) As RESPONSABLE,
0 As IMPORTE 
FROM OPRC T0 WITH(NOLOCK)
WHERE 1=1 
And T0."Active"='Y' 
And COALESCE(T0."ValidFrom",GETDATE())<=GETDATE() 
And COALESCE(T0."ValidTo",GETDATE())>=GETDATE()
