CREATE VIEW SEI_VIEW_DW_MONEDAS AS 
SELECT 
COALESCE(T0."CurrCode",'') As ID,
COALESCE(T0."CurrName",'') As NOMBRE,
COALESCE(T0."DocCurrCod", '') As INTERNACIONAL
FROM OCRN T0 WITH(NOLOCK)
WHERE 1=1 


