CREATE VIEW SEI_VIEW_DW_VIAS_PAGO AS 
SELECT 
COALESCE(T0."PayMethCod",'') As ID,
COALESCE(T0."Descript",'') As NOMBRE,
COALESCE(T0."Type", '') As TIPO,
COALESCE(T0."BankTransf", '') As MEDIO,
COALESCE(T0."DflAccount", '') As CUENTABANCO,
COALESCE(T0."GLAccount", '') As CUENTACONTABLE
FROM OPYM T0 WITH(NOLOCK)
WHERE 1=1 


