CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_ARTICULOS" AS 
SELECT
COALESCE(T0."ItemCode", '') As ID,
COALESCE(T0."ItemName",'') As DESCRIPCION,
CASE WHEN T0."frozenFor"='Y' THEN 'N' ELSE 'S' END As ACTIVO,
COALESCE(T1."CardCode",'') As PROVEEDORCODIGO, 
COALESCE(T1."CardName",'') As PROVEEDORNOMBRE, 
COALESCE(T1."LicTradNum",'') As PROVEEDORNIF,
COALESCE(T1."U_SEIICDW",'') As PROVEEDORICDW,
COALESCE(T2."ItmsGrpNam",'') As GRUPO,
COALESCE(T0."ItemType",'') As TIPO,
'' As "REFERENCIAEXTERNA",
CASE WHEN COALESCE(T0."SellItem",'N')='Y' THEN 'S' ELSE 'N' END As VENTA,
CASE WHEN COALESCE(T0."PrchseItem",'N')='Y' THEN 'S' ELSE 'N' END As COMPRA,
CASE WHEN COALESCE(T0."InvntItem",'N')='Y' THEN 'S' ELSE 'N' END As INVENTARIO,
COALESCE(T0."LastPurPrc",0.0) As ULTIMACOMPRAPRECIO,
COALESCE(T0."LastPurCur",'') As ULTIMACOMPRAMONEDA
FROM OITM T0 
LEFT JOIN OCRD T1 ON T1."CardCode"=T0."CardCode"
INNER JOIN OITB T2 ON T0."ItmsGrpCod" = T2."ItmsGrpCod"
WHERE 1=1 
And T0."frozenFor"<>'Y'

