CREATE VIEW SEI_VIEW_DW_INTERLOCUTORES_DIRECCIONES AS 
SELECT
COALESCE(T0."CardCode",'') As INTERLOCUTOR,
COALESCE(T1."CardType", '') As INTERLOCUTORTIPO,
COALESCE(T1."LicTradNum", '') As INTERLOCUTORNIF,
COALESCE(T0."AdresType",'') As TIPO,
COALESCE(T0."Address",'') As ID,
COALESCE(T0."Address2",'') As NOMBRE2,
COALESCE(T0."Address3", '') As NOMBRE3,
COALESCE(T0."Street", '') As CALLE,
COALESCE(T0."Block", '') As BLOQUE,
COALESCE(T0."City", '') As CIUDAD,
COALESCE(T0."ZipCode", '') As CODIGOPOSTAL,
COALESCE(T0."County", '') As PROVINCIA,
COALESCE(T0."State", '') As ESTADO,
COALESCE(T0."Country", '') As PAIS,
COALESCE(T0."LicTradNum", '') As NIF,
COALESCE(T0."StreetNo", '') As NUMEROCALLE,
COALESCE(T0."Building", '') As EDIFICIO,
COALESCE(T0."TaxOffice", '') As DELEGACIONHACIENDA,
COALESCE(T0."GlblLocNum", '') As GLN,
CASE COALESCE(T0."AdresType",'')
	WHEN 'B' THEN
		CASE WHEN T0."Address"=T1."BillToDef" THEN 'S' ELSE 'N' END 
	ELSE 
		CASE WHEN T0."Address"=T1."ShipToDef" THEN 'S' ELSE 'N' END 
END As PORDEFECTO	
FROM CRD1 T0 WITH(NOLOCK) 
JOIN OCRD T1 WITH(NOLOCK) ON T1."CardCode"=T0."CardCode"
WHERE 1=1 
And T1."frozenFor"<>'Y'
