CREATE VIEW SEI_VIEW_DW_INTERLOCUTORES_CONTACTOS AS 
SELECT
COALESCE(T0."CardCode",'') As INTERLOCUTOR,
COALESCE(T1."CardType", '') As INTERLOCUTORTIPO,
COALESCE(T1."LicTradNum", '') As INTERLOCUTORNIF,
COALESCE(T0."CntctCode",0) As CODIGO,
COALESCE(T0."Name",'') As ID,
COALESCE(T0."FirstName",'') As NOMBRE,
COALESCE(T0."MiddleName", '') As SEGUNDONOMBRE,
COALESCE(T0."LastName", '') As APELLIDO,
COALESCE(T0."Title", '') As TITULO,
COALESCE(T0."Position", '') As POSICION,
COALESCE(T0."Address", '') As DIRECCION, 
COALESCE(T0."Tel1", '') As TELEFONO1,
COALESCE(T0."Tel2", '') As TELEFONO2,
COALESCE(T0."Cellolar", '') As TELEFONOMOVIL,
COALESCE(T0."Fax", '') As FAX,
COALESCE(T0."E_MailL", '') As EMAIL,
COALESCE(T0."EmlGrpCode", '') As EMAILGRUPO,
COALESCE(T0."Pager", '') As BUSCA,
COALESCE(T0."Notes1", '') As OBSERVACIONES1,
COALESCE(T0."Notes2", '') As OBSERVACIONES2,
COALESCE(T0."Password", '') As CLAVEACCESO,
COALESCE(T0."BirthCity", '') As NACIMIENTOCIUDAD,
COALESCE(T0."BirthPlace", '') As NACIMIENTOPAIS,
CONVERT(NVARCHAR,COALESCE(T0."BirthDate", 0), 112) As NACIMIENTOFECHA,
COALESCE(T0."Gender", '') As SEXO,
COALESCE(T0."Profession", '') As PROFESION,
CASE WHEN T0."Name "=T1."CntctPrsn" THEN 'S' ELSE 'N' END As PORDEFECTO,
'N' As CONTACTOFIRMA
FROM OCPR T0 WITH(NOLOCK)
JOIN OCRD T1 WITH(NOLOCK) ON T1."CardCode"=T0."CardCode"
WHERE 1=1 
And T1."frozenFor"<>'Y'

