CREATE VIEW SEI_VIEW_DW_INTERLOCUTORES_BANCOS AS 
SELECT
COALESCE(T0."CardCode",'') As INTERLOCUTOR,
COALESCE(T1."CardType",'') As TIPO,
COALESCE(T0."IBAN",'') As IBAN,
COALESCE(T0."BankCode",'') As BANCO,
COALESCE(T0."Branch", '') As SUCURSAL,
COALESCE(T0."ControlKey", '') As DIGITOSCONTROL,
COALESCE(T0."Account", '') As CUENTANUMERO,
COALESCE(T0."AcctName", '') As CUENTANOMBRE,
COALESCE(T0."Country", '') As PAIS,
COALESCE(T0."Account", '') As CUENTACONTABLE
FROM OCRB T0 WITH(NOLOCK)
JOIN OCRD T1 WITH(NOLOCK) ON T1."CardCode"=T0."CardCode"
WHERE 1=1 
And T1."frozenFor"<>'Y'
