CREATE VIEW SEI_VIEW_DW_TARJETAS_EQUIPOS AS 
SELECT
COALESCE(T0."insID", -1) As ID,
COALESCE(T0."BPType", 'P') As TIPO,
COALESCE(T0."manufSN",'') As NUMFABRICANTE,
COALESCE(T0."internalSN",'') As NUMSERIE,
COALESCE(T0."itemCode",'') As ARTICULO, 
COALESCE(T0."itemName",'') As DESCRIPCION, 
COALESCE(T0."customer",'') As INTERLOCUTOR
FROM OINS T0 WITH(NOLOCK)
WHERE 1=1 


