CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_TASAS_CAMBIO" AS 
SELECT 
COALESCE(T0."RateDate",CURRENT_DATE) As FECHA,
COALESCE(T0."Currency",'') As MONEDA,
COALESCE(T0."Rate", 0) As TASA
FROM ORTT T0
WHERE 1=1 


