CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_CENTROS_COSTE" AS 
SELECT
COALESCE(T0."PrcCode",'') As ID,
COALESCE(T0."PrcName", '') As NOMBRE,
COALESCE(T0."DimCode",	-1) As DIMENSION,
COALESCE(T0."CCOwner",	-1) As RESPONSABLE,
0 As IMPORTE 
FROM OPRC T0
WHERE 1=1 
And T0."Active"='Y' 
And COALESCE(T0."ValidFrom",CURRENT_DATE)<=CURRENT_DATE
And COALESCE(T0."ValidTo",CURRENT_DATE)>=CURRENT_DATE
