CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_BANCOS_PROPIOS" AS 
SELECT 
COALESCE(T0."IBAN",'') As IBAN,
COALESCE(T0."BankCode",'') As BANCO,
COALESCE(T0."Branch", '') As SUCURSAL,
COALESCE(T0."ControlKey", '') As DIGITOSCONTROL,
COALESCE(T0."Account", '') As CUENTANUMERO,
COALESCE(T0."AcctName", '') As CUENTANOMBRE,
COALESCE(T0."Country", '') As PAIS,
COALESCE(T0."GLAccount", '') As CUENTACONTABLE
FROM DSC1 T0 
WHERE 1=1 

