CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_GRUPOS_IMPOSITIVOS" AS 
SELECT
COALESCE(T0."Code",'') As ID,
COALESCE(T0."Name",'') As NOMBRE,
COALESCE(T0."Rate",0) As PORCENTAJE,
COALESCE(T0."Category",'') As CATEGORIA,
CASE WHEN COALESCE(T0."IsEC",'N')='Y' THEN 'S' ELSE 'N' END As INTRACOMUNITARIO
FROM OVTG T0
JOIN VTG1 T1 ON T1."Code"=T0."Code"
WHERE 1=1
And T0."Locked"<>'Y'
And T0."Inactive"<>'Y'
And T1."EffecDate"= (SELECT T."EffecDate" 
					 FROM (SELECT ROW_NUMBER() OVER(ORDER BY X1."EffecDate" DESC) AS ROWN, X1."EffecDate"
					       FROM VTG1 X1 
						   WHERE X1."Code"=T0."Code") AS T
					 WHERE ROWN = 1)