CREATE VIEW "BASEDATOS_HANA"."SEI_VIEW_DW_CUENTAS_CONTABLES" AS 
SELECT 
COALESCE(T0."AcctCode",'') As ID,
COALESCE(T0."AcctName",'') As NOMBRE,
COALESCE(T0."FatherNum",'') As PADRE,
COALESCE(T0."Levels",-1) As NIVEL
FROM OACT T0 
WHERE 1=1 
And T0."Frozen"<>'Y'
And T0."Postable"='Y'